EXPERIMENT: "SPOS-supernetv2_emotion_augmix-cels_SGDW-nesterov_cosine-0.01-noRestart-warmup_scratch"
# [modelname]_[task]_[loss]_[opt]_[lr]_[trick]_[pretrain]
IO: True
SAVE: True
SEED: 42
EVALUATE_FREQ: 1

# TASK: "spos"
# GRAPH: "imagenet"
# ENGINE: "imagenet"
# TRAINER: "imagenet"
NUM_WORKERS: 16
MODEL:
  GPU: [3]
  # BACKBONE: 'shufflenas'
INPUT:
  RESIZE: (112, 112)
  # PAD: 4
  TRAIN_BS: 64
  TEST_BS: 512
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]  
  # RAND_AUG_N: 2
  # RAND_AUG_M: 10
DB:
  PATH: "/home/agent/deep-learning-works/data"
  NUM_CLASSES: 7 #D:702, M:751 MSMT:2012(merge)
  DATA: "emotion"
  DATA_FORMAT: "classification"
  LOADER: "classification"
  USE_TRAIN: True
  USE_TEST: True
TRAIN_TRANSFORM: "AugMix Tensorize Normalize"
TEST_TRANSFORM: "Tensorize Normalize"
SOLVER:
  OPTIMIZER: "SGDW"
  START_EPOCH: 1
  MAX_EPOCHS: 120
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.00004
  MOMENTUM: 0.9
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  NESTEROV: True
  LR_POLICY: "cosine"
  T_0: 120
  # CUSTOM: [['bn', 'wd', 0.0]]
  # MIN_LR: 1e-5
  WARMUP: True
  # GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_SIZE: 5.0
  # PLATEAU_SIZE: 100.0
SPOS:
  EPOCH_TO_CS: 30
  DURATION: 120
RESUME: "/home/agent/SPOS-pytorch/result/SPOS-supernet_emotion_augmix-cels_SGDW-nesterov_cosine-0.5-noRestart-warmup_scratch/2020-03-03_05-12-09/weights/model_119_0.6581.pth"
